### ISSUE TITLE
Some suggested tweaks

### ISSUE THREAD

**Issue by smurphos** [karthikbhupathy13/Metallic_Cyan#1]
Hi, 

Really like this theme particularly the gradients on the menu and panels. But a few things are a bit jarring and I've tweaked a local copy to fix those.

1) Tool tip font size - 10pt, padding - 6px.
2) Got rid of the border around selected/highlighted menu items (deleted 4 instances of _border: 1px solid rgba(90,90, 90,1);_ in the menus section. The border causes an unpleasant 2px jump in the size of the whole menu.

Anyway thanks for a great theme - it's the first I've liked enough to want to tweak to make it my own!

**Comment by karthikbhupathy13** [comment]
Hey friend, thanks a lot for the feedback!!!! :D

Ok. I'll check the tweaks. Currently I have switched to Debian. If
possible, please send me the snapshots of the tweak please. Thanks in
advance!!

**Comment by karthikbhupathy13** [comment]
Hey Friend,
Update done as per your feedback. :+1:
